upcoming:
  - name: Überblick über die Plugin Entwicklung für Kibana
    event: Search Meetup Karlsruhe
    date: Februar 2016
    image: /talks/search-meetup-karlsruhe.png
    url: http://www.meetup.com/de/Search-Meetup-Karlsruhe/events/227548763/
past:
  - name: Überblick über die Plugin Entwicklung für Kibana
    event: Search Meetup Karlsruhe
    date: Februar 2016
    image: /talks/search-meetup-karlsruhe.png
  - name: Überblick über die Plugin Entwicklung für Kibana
    event: Search Meetup Karlsruhe
    date: Februar 2016
    image: /talks/search-meetup-karlsruhe.png
